#!/bin/bash

# --- CONFIGURATION ---
SCRIPT_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &> /dev/null && pwd)
GIT_BRANCH="main"

# Process Management
SERVER_PID_FILE="/tmp/mediamtx.pid"
STREAM_PID_FILE="/tmp/ffmpeg_stream.pid"
SERVER_LOG_FILE="/tmp/mediamtx.log"
STREAM_LOG_FILE="/tmp/ffmpeg_stream.log"

# mediamtx Server (The one we run on the Pi)
MEDIAMTX_CONFIG_FILE="${SCRIPT_DIR}/mediamtx.yml"
MEDIAMTX_BINARY="${SCRIPT_DIR}/mediamtx"
RTSP_PORT="8554"
HLS_PORT="8888"
WEBRTC_PORT="8889"
# This is the latest arm64 build as of Nov 2025
MEDIAMTX_URL="https://github.com/bluenviron/mediamtx/releases/download/v1.15.3/mediamtx_v1.15.3_linux_arm64.tar.gz"

# ffmpeg Stream Client
VIDEO_DEVICE="/dev/video0"
BITRATE="3000k"      # 4 Mbps. (Lower to 2000k if buffering)
FPS=30               # Target framerate
STREAM_NAME="cam"
PUBLISH_USER="admin"
PUBLISH_PASS="mysecretpassword"
RTSP_URL="rtsp://${PUBLISH_USER}:${PUBLISH_PASS}@localhost:${RTSP_PORT}/${STREAM_NAME}"

# --- COLORS ---
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[0;33m'
BLUE='\033[0;34m'
PURPLE='\033[0;35m'
CYAN='\033[0;36m'
NC='\033[0m' # No Color

# --- ASCII ART ---
show_header() {
    tput rmam
    clear
    echo -e "${CYAN}"
    echo '$$\    $$\ $$\           $$\                            $$$$$$\  $$\ $$\                      $$\  '
    echo '$$ |   $$ |\__|          \__|                          $$  __$$\ $$ |\__|                     $$ |'
    echo '$$ |   $$ |$$\  $$$$$$$\ $$\  $$$$$$\  $$$$$$$\        $$ /  \__|$$ |$$\  $$$$$$\  $$$$$$$\ $$$$$$\  '
    echo '\$$\  $$  |$$ |$$  _____|$$ |$$  __$$\ $$  __$$\       $$ |      $$ |$$ |$$  __$$\ $$  __$$\\_$$  _| '
    echo ' \$$\$$  / $$ |\$$$$$$\  $$ |$$ /  $$ |$$ |  $$ |      $$ |      $$ |$$ |$$$$$$$$ |$$ |  $$ | $$ |       ⠀⠀⠀⠀⢀⣴á⣶⡄⠀⠀⠀⠀'
    echo '  \$$$  /  $$ | \____$$\ $$ |$$ |  $$ |$$ |  $$ |      $$ |  $$\ $$ |$$ |$$   ____|$$ |  $$ | $$ |$$\    ⢀⣴⣧⠀⠸⣿⣀⣸⡇⠀⢨⡦⣄'
    echo '   \$  /   $$ |$$$$$$$  |$$ |\$$$$$$  |$$ |  $$ |      \$$$$$$  |$$ |$$ |\$$$$$$$\ $$ |  $$ | \$$$$  |   ⠘⣿⣿⣄⠀⠈⠛⠉⠀⣠⣾⡿⠋'
    echo '    \_/    \__|\_______/ \__| \______/ \__|  \__|       \______/ \__|\__| \_______|\__|  \__|  \____/    ⠀⠀⠈⠛⠿⠶⣶⡶⠿⠟⠉'
    echo ""
    tput smam
    echo -e "  ${PURPLE}Vision Controller v1.1 (ffmpeg + mediamtx)${NC}"
    echo ""
}

# --- PROCESS STATUS ---
check_status() {
    if [ -f "$SERVER_PID_FILE" ] && ps -p $(cat "$SERVER_PID_FILE") > /dev/null; then
        SERVER_STATUS="${GREEN}RUNNING (PID $(cat "$SERVER_PID_FILE"))${NC}"
    else
        SERVER_STATUS="${RED}STOPPED${NC}"
    fi

    if [ -f "$STREAM_PID_FILE" ] && ps -p $(cat "$STREAM_PID_FILE") > /dev/null; then
        STREAM_STATUS="${GREEN}RUNNING (PID $(cat "$STREAM_PID_FILE"))${NC}"
    else
        STREAM_STATUS="${RED}STOPPED${NC}"
    fi
}

# --- FUNCTIONS ---

# 1. Install Dependencies
install_dependencies() {
    echo -e "${YELLOW}Installing dependencies (ffmpeg, v4l-utils, git, wget)...${NC}"
    sudo apt-get update
    sudo apt-get install -y git ffmpeg v4l-utils wget
    echo -e "${GREEN}System packages installed.${NC}"
    echo ""
    
    echo -e "${YELLOW}Downloading latest mediamtx server...${NC}"
    # Download and extract in the current script directory
    wget -O "${SCRIPT_DIR}/mediamtx.tar.gz" "$MEDIAMTX_URL"
    if [ $? -ne 0 ]; then
        echo -e "${RED}Error: Download failed. Check URL or network.${NC}"
        return 1
    fi
    tar -xzvf "${SCRIPT_DIR}/mediamtx.tar.gz" -C "$SCRIPT_DIR" mediamtx mediamtx.yml
    # Rename default config to avoid overwrite
    mv "${SCRIPT_DIR}/mediamtx.yml" "${SCRIPT_DIR}/mediamtx.yml.default"
    rm "${SCRIPT_DIR}/mediamtx.tar.gz"
    chmod +x "$MEDIAMTX_BINARY"
    echo -e "${GREEN}mediamtx binary installed to ${MEDIAMTX_BINARY}${NC}"
    
    echo -e "${YELLOW}Creating configuration file ${MEDIAMTX_CONFIG_FILE}...${NC}"
    cat << EOF > "$MEDIAMTX_CONFIG_FILE"
# This file was auto-generated by vision-controller.sh
# Allows HLS/WebRTC to work in a browser
httpProtocol:
  cors:
    - '*'

# RTSP server (for ffmpeg to publish to)
rtspPort: ${RTSP_PORT}

# HLS server (for browser playback)
hlsPort: ${HLS_PORT}

# WebRTC server (for ultra-low-latency browser playback)
webrtcPort: ${WEBRTC_PORT}

# Define our camera stream "path"
paths:
  ${STREAM_NAME}:
    # Credentials for ffmpeg to publish
    publishUser: ${PUBLISH_USER}
    publishPass: ${PUBLISH_PASS}
EOF
    echo -e "${GREEN}Configuration file created!${NC}"
    echo -e "${GREEN}Installation complete.${NC}"
}

# 2. Start Server
start_server() {
    if [ -f "$SERVER_PID_FILE" ] && ps -p $(cat "$SERVER_PID_FILE") > /dev/null; then
        echo -e "${YELLOW}Server is already running.${NC}"
        return 1
    fi

    if [ ! -f "$MEDIAMTX_BINARY" ]; then
        echo -e "${RED}Error: 'mediamtx' binary not found.${NC}"
        echo -e "${YELLOW}Please run 'Install Dependencies' first.${NC}"
        return 1
    fi
    
    echo -e "${YELLOW}Starting mediamtx server...${NC}"
    nohup "$MEDIAMTX_BINARY" "$MEDIAMTX_CONFIG_FILE" > "$SERVER_LOG_FILE" 2>&1 &
    echo $! > "$SERVER_PID_FILE"
    
    sleep 1
    if ps -p $(cat $SERVER_PID_FILE) > /dev/null; then
        echo -e "${GREEN}Server started successfully! (PID $(cat $SERVER_PID_FILE))${NC}"
        echo "Log available at $SERVER_LOG_FILE"
    else
        echo -e "${RED}Error: Server failed to start. Check log:${NC}"
        cat "$SERVER_LOG_FILE"
        rm -f "$SERVER_PID_FILE"
    fi
}

# 3. Stop Server
stop_server() {
    if [ ! -f "$SERVER_PID_FILE" ]; then
        echo -e "${YELLOW}Server is not running.${NC}"
        return 0
    fi

    local pid=$(cat "$SERVER_PID_FILE")
    echo -e "${YELLOW}Stopping mediamtx server (PID $pid)...${NC}"
    
    if kill -TERM "$pid" 2>/dev/null; then
        rm -f "$SERVER_PID_FILE"
        echo -e "${GREEN}Server stopped.${NC}"
    else
        echo -e "${RED}Error: Could not kill process $pid.${NC}"
        echo "It may have already stopped. Removing stale PID file."
        rm -f "$SERVER_PID_FILE"
    fi
}

# 4. Start Stream
start_stream() {
    if [ -f "$STREAM_PID_FILE" ]; then
        echo -e "${YELLOW}Stream is already running.${NC}"
        return 1
    fi

    if [ ! -f "$SERVER_PID_FILE" ] || ! ps -p $(cat "$SERVER_PID_FILE") > /dev/null; then
        echo -e "${RED}Error: mediamtx server is not running.${NC}"
        echo -e "${YELLOW}Please start the server first.${NC}"
        return 1
    fi
    
    echo -e "${GREEN}Starting ffmpeg stream...${NC}"
    echo -e "${CYAN}Source: ${VIDEO_DEVICE} | Target: ${RTSP_URL}${NC}"
    
    # This is our working ffmpeg command
    # Added -fflags nobuffer to reduce input latency
    local FFMPEG_CMD="ffmpeg \
        -fflags nobuffer \
        -f v4l2 \
        -i ${VIDEO_DEVICE} \
        -vf \"fps=${FPS}\" \
        -c:v h264_v4l2m2m \
        -b:v ${BITRATE} \
        -f rtsp \
        -rtsp_transport tcp \
        ${RTSP_URL}"

    # Start the pipeline in the background
    nohup bash -c "$FFMPEG_CMD" > "$STREAM_LOG_FILE" 2>&1 &
    
    echo $! > "$STREAM_PID_FILE"
    
    sleep 2 
    if ps -p $(cat $STREAM_PID_FILE) > /dev/null; then
        echo -e "${GREEN}Stream started successfully! (PID $(cat $STREAM_PID_FILE))${NC}"
        echo -e "${YELLOW}To see FPS, select 'View Stream Log'.${NC}"
    else
        echo -e "${RED}Error: Stream failed to start. Check log:${NC}"
        cat "$STREAM_LOG_FILE"
        rm -f "$STREAM_PID_FILE"
    fi
}

# 5. Stop Stream
stop_stream() {
    if [ ! -f "$STREAM_PID_FILE" ]; then
        echo -e "${YELLOW}Stream is not running.${NC}"
        return 0
    fi

    local pid=$(cat "$STREAM_PID_FILE")
    echo -e "${YELLOW}Stopping ffmpeg stream (PID $pid)...${NC}"
    
    # ffmpeg responds well to a standard TERM signal
    if kill -TERM "$pid" 2>/dev/null; then
        rm -f "$STREAM_PID_FILE"
        echo -e "${GREEN}Stream stopped.${NC}"
    else
        echo -e "${RED}Error: Could not kill process $pid.${NC}"
        echo "It may have already stopped. Removing stale PID file."
        rm -f "$STREAM_PID_FILE"
    fi
}

# 6. View Stream Log (FPS)
view_stream_log() {
    if [ ! -f "$STREAM_LOG_FILE" ]; then
        echo -e "${RED}No stream log file found.${NC}"
        return 1
    fi
    echo -e "${YELLOW}Showing live ffmpeg log. Look for 'fps='...${NC}"
    echo "(Press Ctrl+C to exit log view)"
    sleep 1
    # -f "follows" the log, -n 50 shows the last 50 lines
    tail -f -n 50 "$STREAM_LOG_FILE"
}

# 7. View Server Log
view_server_log() {
    if [ ! -f "$SERVER_LOG_FILE" ]; then
        echo -e "${RED}No server log file found.${NC}"
        return 1
    fi
    echo -e "${YELLOW}Showing live mediamtx log...${NC}"
    echo "(Press Ctrl+C to exit log view)"
    sleep 1
    tail -f -n 50 "$SERVER_LOG_FILE"
}


# 8. Check Camera
check_camera() {
    if ! command -v v4l2-ctl &> /dev/null; then
        echo -e "${RED}'v4l2-ctl' not found. Run 'Install Dependencies' first.${NC}"
        return 1
    fi
    echo -e "${YELLOW}Checking for V4L2 devices...${NC}"
    local devices
    devices=$(v4l2-ctl --list-devices)
    
    if [ -z "$devices" ]; then
        echo -e "${RED}Error: No V4L2 devices found.${NC}"
    else
        echo -e "${GREEN}Success! Found device(s):${NC}"
        echo "$devices"
        echo -e "${CYAN}Script is configured to use '$VIDEO_DEVICE'.${NC}"
    fi
}

# 9. List Camera Formats
list_camera_formats() {
    if ! command -v v4l2-ctl &> /dev/null; then
        echo -e "${RED}'v4l2-ctl' not found. Run 'Install Dependencies' first.${NC}"
        return 1
    fi
    echo -e "${YELLOW}Listing all supported formats for $VIDEO_DEVICE...${NC}"
    v4l2-ctl --list-formats-ext -d "$VIDEO_DEVICE"
}


# 10. Self-Update
self_update() {
    echo -e "${YELLOW}Attempting to self-update...${NC}"
    local SCRIPT_NAME
    SCRIPT_NAME=$(basename "$0")
    
    if ! git rev-parse --is-inside-work-tree > /dev/null 2>&1; then
        echo -e "${RED}Error: This script is not in a git repository.${NC}"
        return 1
    fi

    echo "Creating temporary updater stub..."
    cat << EOF > ./updater.sh
#!/bin/bash
echo "Fetching updates from git..."
git fetch --all
git reset --hard origin/$GIT_BRANCH
if [ \$? -ne 0 ]; then
    echo -e "${RED}Error: 'git reset' failed. Update aborted.${NC}"
    rm -- "\$0"
    exit 1
fi
echo "Update successful."
echo "Relaunching $SCRIPT_NAME..."
chmod +x "$SCRIPT_NAME"
rm -- "\$0"
exec "./$SCRIPT_NAME"
EOF
    chmod +x ./updater.sh
    echo -e "${GREEN}Handing over to updater. The script will now restart...${NC}"
    exec ./updater.sh
}

# --- MAIN MENU ---
while true; do
    check_status
    show_header
    echo -e "  Server Status: $SERVER_STATUS"
    echo -e "  Stream Status: $STREAM_STATUS"
    echo ""
    echo -e "${CYAN}--- PROCESS ---${NC}"
    echo -e "  ${GREEN}1.${NC} Start Server (mediamtx)"
    echo -e "  ${RED}2.${NC} Stop Server (mediamtx)"
    echo -e "  ${GREEN}3.${NC} Start Stream (ffmpeg)"
    echo -e "  ${RED}4.${NC} Stop Stream (ffmpeg)"
    echo -e "${CYAN}--- DEBUG ---${NC}"
    echo -e "  ${YELLOW}5.${NC} View Stream Log (FPS)"
    echo -e "  ${YELLOW}6.${NC} View Server Log"
    echo -e "  ${PURPLE}7.${NC} Check Camera (V4L2)"
    echo -e "  ${PURPLE}8.${NC} List Camera Formats (Debug)"
    echo -e "${CYAN}--- SYSTEM ---${NC}"
    echo -e "  ${BLUE}9.${NC} Install/Update Dependencies"
    echo -e "  ${BLUE}10.${NC} Update This Script (from GitHub)"
    echo -e "  ${RED}11.${NC} Exit"
    echo ""
    echo -e "${YELLOW}Choose an option [1-11]:${NC}"
    read -r choice
    
    case $choice in
        1) start_server ;;
        2) stop_server ;;
        3) start_stream ;;
        4) stop_stream ;;
        5) view_stream_log ;;
        6) view_server_log ;;
        7) check_camera ;; # Fixed the typo here
        8) list_camera_formats ;;
        9) install_dependencies ;;
        10) self_update ;;
        11)
            echo "Stopping processes..."
            stop_stream
            stop_server
            echo "Exiting."
            exit 0
            ;;
        *)
            echo -e "${RED}Invalid option. Please try again.${NC}"
            ;;
    esac
    echo ""
    echo "Press Enter to return to the menu..."
    read -r
done